### ISSUE TITLE
Implement a DHT Bootstrapper

### ISSUE THREAD

**Issue by dennis-tra** [plprobelab/go-kademlia#110]
ETA: 2023-09-08

Description: To test the interplay of all the different pieces, we thought of putting together a bootstrapper node. The assumption is that it has a limited feature set, and we could get away with a partial implementation of a few internal modules. The main requirements are:

- Respond to FIND_NODE RPCs and return closer peers
- Keep the own routing table up-to-date

Children:

- https://github.com/libp2p/go-libp2p-kad-dht/issues/881
- https://github.com/libp2p/go-libp2p-kad-dht/issues/882

**Comment by BigLep** [comment]
Is the intent that this would be a binary that Bifrost could run instead of Kubo (similar to how we have a rust-libp2p based bootstrapper)?

I think that makes sense.  Let make sure though that we're accounting for the distribution (Docker?) and operational side (e.g., metrics)

**Comment by dennis-tra** [comment]
Done in https://github.com/plprobelab/musa

I don't consider the load test as part of the implementation, therefore, I removed https://github.com/libp2p/go-libp2p-kad-dht/issues/883 from the list of children. See that issue for the next steps.
