### ISSUE TITLE
Rename go-kademlia to go-libdht

### ISSUE THREAD

**Issue by guillaumemichel** [plprobelab/go-kademlia#113]
Following up on https://github.com/plprobelab/go-kademlia/issues/84, we want to rename `go-kademlia` to `go-libdht`.

**Comment by iand** [comment]
On https://github.com/plprobelab/go-kademlia/pull/114 we discussed creating a new repo instead and migrating core types to it.

Can we make a list of what moves to go-libdht and what could be moved to go-libp2p-kad-dht?

**Comment by iand** [comment]
See #120

**Comment by iand** [comment]
We created a new repo for go-libdht and moved core types from go-kademlia
