### ISSUE TITLE
Define Public IPFS DHT Interface

### ISSUE THREAD

**Issue by iand** [plprobelab/go-kademlia#24]
# Description

Define a clean interface to the dht with an implementation that configures a scheduler, starts it and keeps it running to service requests. This is the interface that Kubo would use when integrated.

See if https://hackmd.io/@iandavis/SyjmgYkrh provides anything useful here.

**Comment by guillaumemichel** [comment]
The goal of this repository is to provide generic building blocks to build any Kademlia DHT.

Defining the Public **IPFS** DHT Interface should probably happen in https://github.com/ipfs/boxo

**Comment by iand** [comment]
I think the IPFS DHT interface is orthogonal to this issue. I was thinking that we need to define how to instantiate the scheduler and keep it running. I'm not sure that is a client responsibility.

**Comment by guillaumemichel** [comment]
I would argue that it is the client responsibility to manage the scheduler. However the IPFS DHT should have a standard interface setting up the scheduler. This part should live in https://ipfs/boxo, and it is where all interactions between boxo and Kademlia (including multi thread support) should be defined. IPFS builders should use the IPFS DHT Interface, they don't have to know anything about scheduling or single/multithread.

kubo and boxo are multithread, but a single thread implementation would interact differently with the scheduler of the go-kademlia implementation generally.
