### ISSUE TITLE
Bootstrap process

### ISSUE THREAD

**Issue by guillaumemichel** [plprobelab/go-kademlia#47]
Once connected to a first peer in the DHT network, the DHT node must lookup its own key and fill its routing table's buckets.

One way to implement it is to run the [routing table refresh](https://github.com/libp2p/go-libp2p-kad-dht/tree/ee95d1ab03c47aab03218e18d07483f51e7787e4/rtrefresh). Alternatively it is possible to lookup for its own key, and for _random_ peer ids in each of its bucket, in order to populate the buckets.

cc: @iand 

Related to https://github.com/plprobelab/go-kademlia/issues/2 and https://github.com/plprobelab/go-kademlia/issues/45

**Comment by iand** [comment]
Added as a subtask of #2
