### ISSUE TITLE
Only add reachable peers to the routing table

### ISSUE THREAD

**Issue by guillaumemichel** [plprobelab/go-kademlia#53]
Ensure that we only add nodes that are actually able to answer our Kademlia requests to the routing table. When refreshing the routing table, we should make sure that the nodes still answer Kademlia requests correctly.

In the IPFS `KadDHT`, this check can be done by sending a Kademlia `GET_PROVIDERS` or `FIND_NODE` RPC, and if the probed peer provides a valid response we can add/keep it in the routing table.

## References
* https://github.com/libp2p/go-libp2p-kad-dht/issues/811
* https://github.com/libp2p/go-libp2p-kad-dht/pull/820
* https://github.com/libp2p/go-libp2p-kad-dht/pull/810

**Comment by iand** [comment]
This is covered by the design for the candidate queue in #45

**Comment by iand** [comment]
Done
